version: '3.8'
services:
# rdb的容器
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: default
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql

# llm的容器
  ollama-embedding:
    image: ollama/ollama:latest
    container_name: ollama-embedding
    ports:
      - "11435:11434"
    volumes:
      - ./volumes/ollama_embedding:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      NVIDIA_VISIBLE_DEVICES: all

  ollama-chat:
    image: ollama/ollama:latest
    container_name: ollama-chat
    ports:
      - "11434:11434"
    volumes:
      - ./volumes/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      NVIDIA_VISIBLE_DEVICES: all

# asr的容器，这个容器是docker上没有镜像的，在本项目FastWhisperService下自己制作镜像
  whisper:
    image: myadzusa/whisper:latest
    container_name: whisper-service
    ports:
      - "10350:10350"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    environment:
      NVIDIA_VISIBLE_DEVICES: all

# tts的容器
  gpt-sovits:
    image: xxxxrt666/gpt-sovits:latest-cu128-lite
    container_name: gpt-sovits-cu128-lite
    environment:
      - is_half=true
    volumes:
      - ./volumes/sovits/ref:/workspace/GPT-SoVITS/ref
      - ./volumes/sovits/models/G2PWModel:/workspace/models/G2PWModel
      - ./volumes/sovits/models/asr_models:/workspace/models/asr_models
      - ./volumes/sovits/models/uvr5_weights:/workspace/models/uvr5_weights
      - ./volumes/sovits/models/pretrained_models:/workspace/models/pretrained_models
      - ./volumes/sovits/GPT_weights:/workspace/GPT-SoVITS/GPT_weights
      - ./volumes/sovits/SoVITS_weights:/workspace/GPT-SoVITS/SoVITS_weights
      - ./volumes/sovits/configs:/workspace/GPT-SoVITS/GPT_SoVITS/configs
    working_dir: /workspace/GPT-SoVITS
    command: >
      bash -c "
      rm -rf ./GPT_SoVITS/pretrained_models &&
      ln -sf /workspace/models/pretrained_models ./GPT_SoVITS/pretrained_models &&
      ln -sf /workspace/models/G2PWModel ./GPT_SoVITS/text/G2PWModel &&
      ln -sf /workspace/models/asr_models ./tools/asr/models &&
      ln -sf /workspace/models/uvr5_weights ./tools/uvr5/uvr5_weights &&
      python api_v2.py -a 0.0.0.0 -p 9880 -c GPT_SoVITS/configs/tts_infer.yaml"
    #command: ["python", "GPT-SoVITS/api.py"]
    ports:
      - "9880:9880"
#      - "9871:9871"
#      - "9872:9872"
#      - "9873:9873"
#      - "9874:9874"
    shm_size: "16G"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]
    stdin_open: true
    tty: true
    restart: unless-stopped
# vdb的容器
  etcd:
    container_name: milvus-etcd
    #image: milvusdb/etcd:3.5.5-r2
    image: milvusdb/etcd:latest
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_DATA_DIR=/etcd
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - ./volumes/miluvs/etcd:/etcd
    #command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: [ "CMD", "etcdctl", "endpoint", "health" ]
      interval: 30s
      timeout: 20s
      retries: 3
  minio:
    container_name: milvus-minio
    #image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ./volumes/miluvs/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.5.10
    command: [ "milvus", "run", "standalone" ]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ./volumes/miluvs/milvus:/var/lib/milvus
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9091/healthz" ]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

  elasticsearch:
    image: elasticsearch:8.18.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx2g

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin114514
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/home/node/.n8n/database.sqlite
      - TZ=Asia/Shanghai
    volumes:
      - ./volumes/n8n/n8n_data:/home/node/.n8n
      - ./AstrolithaBackend/uploads/rag:/data/uploads/rag
networks:
  default:
    name: astrolitha