# spring框架的配置，包含AI的部分
server:
  address: 0.0.0.0
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 500MB
  application:
    name: AstrolithaBackend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/default?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456
    hikari:
      initialization-fail-timeout: -1
  elasticsearch:
    uris: http://elasticsearch:9200
  ai:
    ollama:
      base-url: http://ollama-chat:11434
      sub-url: http://ollama-chat:11435
      chat:
        model: deepseek-r1:7b
      agent:
        model: llama3.1:8b
      embedding:
        model: bge-m3:latest
logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: trace
# mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# 线程池配置
async-task:
  execution:
    pool:
      core-size: 4
      max-size: 10


# 本项目自定义的一些变量
app:
  resource:
    location:
      rag:
        origin: file:./uploads/rag/
        mapping: /uploads/rag/**

ollama:
  warmup:
    - name: llama3.1:8b
      url: http://ollama-chat:11434/api/generate
      prompt: ping
    - name: bge-m3:latest
      url: http://ollama-embedding:11435/api/embeddings
      prompt: ping
milvus:
  uri: http://standalone:19530
  token: root:Milvus
  database: user_vector_database

microservice:
  gpt-sovits:
    url: http://gpt-sovits:9880/tts
  whisper:
    url: http://whisper:10350