# spring框架的配置，包含AI的部分
server:
  address: 0.0.0.0
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 500MB
  application:
    name: AstrolithaBackend
  sql:
    init:
      schema-locations: classpath:init.sql
      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/default?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      initialization-fail-timeout: -1
  elasticsearch:
    uris: http://localhost:9200
  ai:
    ollama:
      base-url: http://localhost:11434
      sub-url: http://localhost:11435
      chat:
        model: deepseek-r1:7b
      agent:
        model: llama3.1:8b
      embedding:
        model: bge-m3:latest
logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: trace
# mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# 线程池配置
async-task:
  execution:
    pool:
      core-size: 4
      max-size: 32


# 本项目自定义的一些变量
app:
  resource:
    location:
      rag:
        origin: file:./uploads/rag/
        mapping: /uploads/rag/**

ollama:
  warmup:
    - name: llama3.1:8b
      url: http://localhost:11434/api/generate
      prompt: ping
    - name: bge-m3:latest
      url: http://localhost:11435/api/embeddings
      prompt: ping

milvus:
  uri: http://localhost:19530
  token: root:Milvus
  database: default
  collection: default_collection
  threshold: 0.35

microservice:
  gpt-sovits:
    url: http://localhost:9880/tts
  whisper:
    url: http://localhost:10350